# Generated by Django 5.0 on 2024-11-18 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Designer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Clothing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("style_number", models.CharField(max_length=50, unique=True)),
                ("image", models.ImageField(upload_to="clothing_images/")),
                ("material", models.TextField()),
                ("color", models.CharField(max_length=50)),
                ("import_date", models.DateTimeField(auto_now_add=True)),
                (
                    "excel_file",
                    models.FileField(blank=True, null=True, upload_to="excel_files/"),
                ),
                (
                    "designer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clothes",
                        to="clothes.designer",
                    ),
                ),
            ],
        ),
    ]
